export const
      TYPE_NORMAL = Symbol(`TYPE_NORMAL`),
      TYPE_FIRE = Symbol(`TYPE_FIRE`),
      TYPE_WATER = Symbol(`TYPE_WATER`),
      TYPE_ELECTRIC = Symbol(`TYPE_ELECTRIC`),
      TYPE_GRASS = Symbol(`TYPE_GRASS`),
      TYPE_ICE = Symbol(`TYPE_ICE`),
      TYPE_FIGHTING = Symbol(`TYPE_FIGHTING`),
      TYPE_POISON = Symbol(`TYPE_POISON`),
      TYPE_GROUND = Symbol(`TYPE_GROUND`),
      TYPE_FLYING = Symbol(`TYPE_FLYING`),
      TYPE_PSYCHIC = Symbol(`TYPE_PSYCHIC`),
      TYPE_BUG = Symbol(`TYPE_BUG`),
      TYPE_ROCK = Symbol(`TYPE_ROCK`),
      TYPE_GHOST = Symbol(`TYPE_GHOST`),
      TYPE_DRAGON = Symbol(`TYPE_DRAGON`),
      TYPE_DARK = Symbol(`TYPE_DARK`),
      TYPE_STEEL = Symbol(`TYPE_STEEL`);
